[package]
name = "fyi_progress"
version = "0.2.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
indexmap = "1.3.*"
itoa = "0.4.*"
num-integer = "*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[features]
default = []

[dev-dependencies]
criterion = "*"
rayon = "*"

[[bench]]
name = "fp_lapsed"
harness = false

[[example]]
name = "progress"
