[package]
name = "fyi_progress"
version = "0.2.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
bitflags = "1.2.*"
indexmap = "1.3.*"
itoa = "0.4.*"
lazy_static = "1.4.*"
num-traits = "0.2.*"
rayon = "1.3.*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[features]
default = []

[dev-dependencies]
criterion = "*"

# [[bench]]
# name = "fm_ansi_code"
# harness = false
