[package]
name = "fyi_menu"
version = "0.3.8"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies.chrono]
version = "0.4.*"
optional = true

[dependencies.libdeflater]
version = "0.5.*"
optional = true

[dependencies.fyi_msg]
path = "../fyi_msg"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_argue"
harness = false

[[bench]]
name = "fm_keykind"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[[example]]
name = "bash"

[[example]]
name = "man"

[features]
default = []
bashman = [ "chrono", "libdeflater" ]
