[package]
name = "fyi_menu"
version = "0.3.4"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
ahash = "0.4.*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[dependencies.packed_simd]
version = "0.3.*"
optional = true

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_argue"
harness = false

[[bench]]
name = "fm_keykind"
harness = false

[[bench]]
name = "fm_keymaster"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[features]
default = []
simd = [ "packed_simd", "ahash/specialize", "criterion/real_blackbox" ]
