[package]
name = "fyi_menu"
version = "0.2.7"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies.fyi_msg]
path = "../fyi_msg"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_arglist"
harness = false
