[workspace]
members = [
	"fyi",
    "fyi_core",
    "fyi_msg",
    "fyi_witch",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
rpath = false
debug-assertions = false
panic = "abort"
incremental = false
overflow-checks = true
