[workspace]
members = [
	"fyi",
	"fyi_menu",
    "fyi_msg",
    "fyi_witcher",
]

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
