[workspace]
members = [
	"fyi",
    "fyi_msg",
    "fyi_progress",
    "fyi_witcher",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
debug-assertions = false
incremental = false
overflow-checks = false
panic = "abort"
rpath = false
