.TH FYI "1" "November 2020" "FYI v0.3.6" "User Commands"
.SH NAME
FYI \- Manual page for fyi v0.3.6.
.SH DESCRIPTION
A dead\-simple CLI status message printer for use in BASH scripts, etc.
.SS USAGE:
.TP
fyi <SUBCOMMAND> [FLAGS]
.RE
fyi <SUBCOMMAND> \-\-help \fI(to see subcommand usage)\fR
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS SUBCOMMANDS:
.TP
\fBhelp\fR
Print help information.
.TP
\fBblank\fR
Print blank line(s).
.TP
\fBconfirm\fR
Ask a Yes/No question, exiting 0 or 1 respectively.
.TP
\fBprint\fR
Print a message without a prefix (or with a custom one).
.TP
\fBcrunched\fR
Crunched: Hello World
.TP
\fBdebug\fR
Debug: Hello World
.TP
\fBdone\fR
Done: Hello World
.TP
\fBerror\fR
Error: Hello World
.TP
\fBinfo\fR
Info: Hello World
.TP
\fBnotice\fR
Notice: Hello World
.TP
\fBsuccess\fR
Success: Hello World
.TP
\fBtask\fR
Task: Hello World
.TP
\fBwarning\fR
Warning: Hello World
