/*!
# FYI: CLI
*/

use argyle::argue;
use crate::FyiError;
use dactyl::traits::BytesToUnsigned;
use fyi_msg::{
	CliCommandArg,
	Msg,
	MsgKind,
};
use std::{
	num::NonZeroUsize,
	process::ExitCode,
};



// Flags generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/flags.rs"));

/// # Remaining CLI Args.
type RemainingArgs = std::iter::Skip<std::env::ArgsOs>;



#[derive(Debug, Clone, Copy)]
/// # Message Settings.
///
/// Most of these settings will get embedded into the `Msg` itself, but there
/// are a couple parts that do not get referenced until print time.
pub(super) struct Settings {
	/// # Flags.
	flags: Flags,

	/// # Exit.
	exit: ExitCode,
}

impl Settings {
	/// # Exit Code.
	pub(super) fn exit(self) -> Result<(), FyiError> {
		if self.exit == ExitCode::SUCCESS { Ok(()) }
		else { Err(FyiError::Passthrough(self.exit)) }
	}

	/// # Indent?
	const fn indent(self) -> bool { self.flags.contains(Flags::Indent) }

	/// # Stderr?
	pub(super) const fn stderr(self) -> bool { self.flags.contains(Flags::Stderr) }

	/// # Timestamp?
	const fn timestamp(self) -> bool { self.flags.contains(Flags::Timestamp) }

	/// # Default Yes?
	pub(super) const fn yes(self) -> bool { self.flags.contains(Flags::Yes) }

	/// # New.
	const fn new() -> Self {
		Self { flags: Flags::None, exit: ExitCode::SUCCESS }
	}
}



/// # Parse Message Kind.
pub(super) fn parse_kind() -> Result<(MsgKind, RemainingArgs), FyiError> {
	let mut args = CliCommandArg::args_os();

	// The first result must be a subcommand or help/version flag.
	let kind = match args.next() {
		Some(CliCommandArg::Blank) =>    MsgKind::Blank,
		Some(CliCommandArg::Confirm) =>  MsgKind::Confirm,
		Some(CliCommandArg::Custom) =>   MsgKind::Custom,
		Some(CliCommandArg::Aborted) =>  MsgKind::Aborted,
		Some(CliCommandArg::Crunched) => MsgKind::Crunched,
		Some(CliCommandArg::Debug) =>    MsgKind::Debug,
		Some(CliCommandArg::Done) =>     MsgKind::Done,
		Some(CliCommandArg::Error) =>    MsgKind::Error,
		Some(CliCommandArg::Found) =>    MsgKind::Found,
		Some(CliCommandArg::Info) =>     MsgKind::Info,
		Some(CliCommandArg::Notice) =>   MsgKind::Notice,
		Some(CliCommandArg::Review) =>   MsgKind::Review,
		Some(CliCommandArg::Skipped) =>  MsgKind::Skipped,
		Some(CliCommandArg::Success) =>  MsgKind::Success,
		Some(CliCommandArg::Task) =>     MsgKind::Task,
		Some(CliCommandArg::Warning) =>  MsgKind::Warning,
		Some(CliCommandArg::Version) =>  return Err(FyiError::PrintVersion),
		Some(CliCommandArg::Other(_) | CliCommandArg::OtherOs(_)) | None => return Err(FyiError::PrintHelp(MsgKind::None)),
	};

	Ok((kind, args.into_inner()))
}

/// # Parse and Print Blanks!
pub(super) fn parse_blank(args: RemainingArgs) -> Result<(), FyiError> {
	argue! {
		Help   "-h" "--help",
		Stderr      "--stderr",
		@options
		Count  "-c" "--count",
	}

	// The first arg is always skipped, the second we read earlier.
	let mut stderr = false;
	let mut count = NonZeroUsize::MIN;
	for arg in ArgumentIter::new(args) {
		match arg {
			Argument::Help => return Err(FyiError::PrintHelp(MsgKind::Blank)),
			Argument::Stderr => { stderr = true; },
			Argument::Count(s) =>
				if let Some(s) = NonZeroUsize::btou(s.trim().as_bytes()) {
					count = NonZeroUsize::max(count, s);
				},

			// Nothing else is relevant here.
			Argument::Other(_) | Argument::OtherOs(_) => {},
		}
	}

	// Print it!
	let lines = "\n".repeat(count.get());
	if stderr { eprint!("{lines}"); }
	else { print!("{lines}"); }

	Ok(())
}

/// # Parse Message.
pub(super) fn parse_msg(kind: MsgKind, args: RemainingArgs)
-> Result<(Msg, Settings), FyiError> {
	argue! {
		Help      "-h" "--help",
		Indent    "-i" "--indent",
		Stderr         "--stderr",
		Timestamp "-t" "--timestamp",
		Yes       "-y" "--yes",
		@options
		Color     "-c" "--prefix-color",
		Prefix    "-p" "--prefix",
		Exit      "-e" "--exit",
	}

	let mut msg = None;
	let mut prefix = String::new();
	let mut color = 199_u8;
	let mut flags = Settings::new();
	for arg in ArgumentIter::new(args) {
		match arg {
			Argument::Help => return Err(FyiError::PrintHelp(kind)),
			Argument::Indent => { flags.flags.set(Flags::Indent); },
			Argument::Stderr => { flags.flags.set(Flags::Stderr); },
			Argument::Timestamp => { flags.flags.set(Flags::Timestamp); },
			Argument::Yes => { flags.flags.set(Flags::Yes); },

			Argument::Color(s) =>
				if let Some(s) = u8::btou(s.trim().as_bytes()) { color = s; },
			Argument::Prefix(s) => { prefix = s; },
			Argument::Exit(s) =>
				if let Some(s) = u8::btou(s.trim().as_bytes()) { flags.exit = s.into(); },

			Argument::Other(s) =>
				if msg.is_none() { msg.replace(s); }
				else { return Err(FyiError::InvalidCli(kind)); },

			Argument::OtherOs(_) => return Err(FyiError::InvalidCli(kind)),
		}
	}

	let msg = msg.ok_or(FyiError::NoMessage)?;
	let msg =
		if matches!(kind, MsgKind::Custom) {
			let color = fyi_msg::AnsiColor::from_u8(color);
			Msg::new((&prefix, color), msg)
		}
		else { Msg::new(kind, msg) }
			.with_timestamp(flags.timestamp())
			.with_indent(u8::from(flags.indent()))
			.with_newline(true);

	Ok((msg, flags))
}
