[package]
name = "fyi_msg"
version = "0.9.6"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "Simple ANSI-formatted, prefixed messages for console printing."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
readme = "README.md"
exclude = [ "examples" ]

[package.metadata.docs.rs]
features = [ "fitted", "progress", "timestamps" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[dependencies]
dactyl = "0.3.*"

[dependencies.ahash]
version = "0.7.*"
optional = true

[dependencies.atomic]
version = "0.5.*"
optional = true

[dependencies.bytecount]
version = "0.6.*"
optional = true

[dependencies.parking_lot]
version = "0.12.*"
optional = true

[dependencies.term_size]
version = "0.3.*"
optional = true

[dependencies.time]
version = "0.3.*"
default-features = false
features = [ "std", "local-offset" ]
optional = true

[dependencies.unicode-width]
version = "0.1.*"
optional = true

[dev-dependencies]
brunch = "0.2.*"
rayon = "1.5.*"

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_buffer_mut"
harness = false

[[bench]]
name = "fm_fitted"
harness = false

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_msg_fitted"
harness = false

[[bench]]
name = "fm_msg_timestamps"
harness = false

[features]
# This adds a few additional MsgKinds relevant only to the main FYI binary.
# There is no point enabling this in other crates.
bin_kinds = []

# Add width-fitting support to the Msg struct, i.e. Msg.fitted().
fitted = [ "unicode-width" ]

# This only applies when "progless" is also enabled.
parking_lot_mutex = [ "parking_lot" ]

# Make use of the "progless" bar.
progress = [ "ahash", "atomic", "bytecount", "fitted", "term_size" ]

# Add timestamp support to messages.
timestamps = [ "time" ]
