[package]
name = "fyi_msg"
version = "0.3.0"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
chrono = "0.4.*"
ustr = "0.7.*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_bufrange"
harness = false

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[[example]]
name = "msg"
