[package]
name = "fyi_msg"
version = "0.6.2"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Lib version of FYI."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]
optional = true

[dependencies.dactyl]
git = "https://github.com/Blobfolio/dactyl.git"
tag = "v0.1.0"

[dependencies.unicode-width]
version = "0.1.*"
optional = true

[dev-dependencies.brunch]
git = "https://github.com/Blobfolio/brunch.git"
tag = "v0.1.0"

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_buffer_mut"
harness = false

[[bench]]
name = "fm_fitted"
harness = false

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_msg_fitted"
harness = false

[[bench]]
name = "fm_msg_timestamps"
harness = false

[[example]]
name = "msg"

[features]
# This adds a few additional MsgKinds relevant only to the main FYI binary.
# There is no point enabling this in other crates.
bin_kinds = []

# Add width-fitting support to the Msg struct, i.e. Msg.fitted().
fitted = [ "unicode-width" ]

# Add timestamp support to messages.
timestamps = [ "chrono" ]
