[package]
name = "fyi_msg"
version = "0.3.4"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
ahash = "0.4.*"
chrono = "0.4.*"

[dependencies.packed_simd]
version = "0.3.*"
optional = true

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[[example]]
name = "msg"

[features]
default = []
simd = [ "packed_simd", "ahash/specialize", "criterion/real_blackbox" ]
