[package]
name = "fyi_msg"
version = "0.7.0"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Lib version of FYI."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies]
dactyl = "0.1.*"

[dependencies.ahash]
version = "0.7.*"
optional = true

[dependencies.bytecount]
version = "0.6.*"
optional = true

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]
optional = true

[dependencies.num-integer]
version = "0.1.*"
optional = true

[dependencies.term_size]
version = "0.3.*"
optional = true

[dependencies.unicode-width]
version = "0.1.*"
optional = true

[dev-dependencies]
brunch = "0.1.*"
rayon = "1.5.*"

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_buffer_mut"
harness = false

[[bench]]
name = "fm_fitted"
harness = false

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_msg_fitted"
harness = false

[[bench]]
name = "fm_msg_timestamps"
harness = false

[[example]]
name = "msg"

[[example]]
name = "progless-par"

[[example]]
name = "progless-serial"

[features]
# This adds a few additional MsgKinds relevant only to the main FYI binary.
# There is no point enabling this in other crates.
bin_kinds = []

# Add width-fitting support to the Msg struct, i.e. Msg.fitted().
fitted = [ "unicode-width" ]

# Make use of the "progless" bar.
progress = [ "ahash", "bytecount", "fitted", "num-integer", "term_size" ]

# Add timestamp support to messages.
timestamps = [ "chrono", "num-integer" ]
