[package]
name = "fyi_msg"
version = "0.5.0"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Lib version of FYI."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies]
unicode-width = "0.1.*"

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dependencies.fyi_num]
path = "../fyi_num"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_buffer"
harness = false

[[example]]
name = "msg"
