[package]
name = "fyi_msg"
version = "0.5.2"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Lib version of FYI."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dependencies.fyi_num]
path = "../fyi_num"

[dependencies.unicode-width]
version = "0.1.*"
optional = true

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_buffer"
harness = false

[[example]]
name = "msg"

[features]
default = []

# This adds a few additional MsgKinds relevant only to the main FYI binary.
# There is no point enabling this in other crates.
bin_kinds = []

# Add width-capping support to the Msg struct.
fitted = [ "unicode-width" ]
