[package]
name = "fyi_msg"
version = "0.3.9"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
ahash = "0.5.*"
chrono = "0.4.*"

[dev-dependencies]
criterion = "*"
num-format = "0.4.*"
rand = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_nice_int"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[[example]]
name = "msg"
