[package]
name = "fyi_msg"
version = "0.2.1"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
bytes = "0.5.*"
chrono = "0.4.*"
memchr = "2.3.*"
unicode-width = "0.1.*"

[dependencies.bytecount]
version = "0.6.*"
default-features = false
features = [ "runtime-dispatch-simd" ]

[dependencies.smallvec]
version = "1.4.*"
default-features = false
features = [ "write" ]

[features]
default = []

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_msgbuf"
harness = false

[[bench]]
name = "fm_utility"
harness = false
