[package]
name = "fyi_msg"
version = "0.2.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
bitflags = "1.2.*"
chrono = "0.4.*"
itoa = "0.4.*"
lazy_static = "1.4.*"
num-traits = "0.2.*"
regex = "1.3.*"
term_size = "0.3.*"
unicode-width = "0.1.*"

[dependencies.bytecount]
version = "0.6.*"
default-features = false
features = [ "runtime-dispatch-simd" ]

[dependencies.casual]
version = "0.1.*"
optional = true

[features]
default = []
interactive = [ "casual" ]
stdout_sinkhole = []

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fm_ansi_code"
harness = false

[[bench]]
name = "fm_girth_ext"
harness = false

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_timestamp"
harness = false

[[bench]]
name = "fm_strip_ansi"
harness = false

[[bench]]
name = "fm_whitespace"
harness = false
