[package]
name = "fyi_msg"
version = "0.4.2"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Lib version of FYI."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies]
ahash = "0.6.*"

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dev-dependencies]
criterion = "*"
num-format = "0.4.*"
rand = "*"

[[bench]]
name = "fm_msg"
harness = false

[[bench]]
name = "fm_buffer"
harness = false

[[bench]]
name = "fm_nice_int"
harness = false

[[bench]]
name = "fm_utility"
harness = false

[[example]]
name = "msg"
