.TH "FYI BLANK" "1" "June 2025" "fyi blank v2.3.0" "User Commands"
.SH NAME
BLANK \- Manual page for fyi blank v2.3.0.
.SH DESCRIPTION
Print blank line(s).
.SS USAGE:
.TP
fyi blank [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-stderr\fR
Print to STDERR instead of STDOUT.
.SS OPTIONS:
.TP
\fB\-c\fR, \fB\-\-count\fR <NUM>
Number of empty lines to print. [default: 1]
