.TH "FYI CONFIRM" "1" "March 2022" "confirm v0.9.5" "User Commands"
.SH NAME
confirm \- Manual page for confirm v0.9.5.
.SH DESCRIPTION
Ask a Yes/No question using the built\-in prefix "confirm".
.SS USAGE:
.TP
fyi confirm [FLAGS] <MSG>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-i\fR, \fB\-\-indent\fR
Indent the line.
.TP
\fB\-t\fR, \fB\-\-timestamp\fR
Include a timestamp.
.SS <MSG>:
.TP
The message!
