.TH "FYI FOUND" "1" "June 2025" "fyi found v2.3.0" "User Commands"
.SH NAME
FOUND \- Manual page for fyi found v2.3.0.
.SH DESCRIPTION
Found: Hello World
.SS USAGE:
.TP
fyi found [FLAGS] [OPTIONS] <MSG>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-i\fR, \fB\-\-indent\fR
Indent the line.
.TP
\fB\-\-stderr\fR
Print to STDERR instead of STDOUT.
.TP
\fB\-t\fR, \fB\-\-timestamp\fR
Include a timestamp.
.SS OPTIONS:
.TP
\fB\-e\fR, \fB\-\-exit\fR <NUM>
Exit with this code (0\-255) after printing. [default: 0]
.SS TRAILING:
.TP
\fB<MSG>\fR
The message!
