.TH "FYI DEBUG" "1" "November 2022" "debug v0.10.3" "User Commands"
.SH NAME
debug \- Manual page for debug v0.10.3.
.SH DESCRIPTION
Debug: Hello World
.SS USAGE:
.TP
fyi debug [FLAGS] [OPTIONS] <MSG>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-i\fR, \fB\-\-indent\fR
Indent the line.
.TP
\fB\-\-stderr\fR
Print to STDERR instead of STDOUT.
.TP
\fB\-t\fR, \fB\-\-timestamp\fR
Include a timestamp.
.SS OPTIONS:
.TP
\fB\-e\fR, \fB\-\-exit\fR <NUM>
Exit with this status code after printing. [default: 0]
.SS <MSG>:
.TP
The message!
