.TH "FYI CONFIRM" "1" "August 2025" "fyi confirm v2.3.1" "User Commands"
.SH NAME
CONFIRM \- Manual page for fyi confirm v2.3.1.
.SH DESCRIPTION
Ask a Yes/No question using the built\-in prefix "confirm".
.SS USAGE:
.TP
fyi confirm [FLAGS] <MSG>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-i\fR, \fB\-\-indent\fR
Indent the line.
.TP
\fB\-t\fR, \fB\-\-timestamp\fR
Include a timestamp.
.TP
\fB\-y\fR, \fB\-\-yes\fR
Default yes (rather than no).
.SS TRAILING:
.TP
\fB<MSG>\fR
The message!
