.TH "FYI" "1" "August 2025" "fyi v2.3.1" "User Commands"
.SH NAME
FYI \- Manual page for fyi v2.3.1.
.SH DESCRIPTION
A dead\-simple CLI status message printer for use in BASH scripts, etc.
.SS USAGE:
.TP
fyi [SUBCOMMAND] [FLAGS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS SUBCOMMANDS:
.TP
\fBaborted\fR
Aborted: Hello World
.TP
\fBblank\fR
Print blank line(s).
.TP
\fBconfirm\fR
Ask a Yes/No question using the built\-in prefix "confirm".
.TP
\fBcrunched\fR
Crunched: Hello World
.TP
\fBdebug\fR
Debug: Hello World
.TP
\fBdone\fR
Done: Hello World
.TP
\fBerror\fR
Error: Hello World
.TP
\fBfound\fR
Found: Hello World
.TP
\fBinfo\fR
Info: Hello World
.TP
\fBnotice\fR
Notice: Hello World
.TP
\fBprint\fR
Print a message without a prefix (or with a custom one).
.TP
\fBreview\fR
Review: Hello World
.TP
\fBskipped\fR
Skipped: Hello World
.TP
\fBsuccess\fR
Success: Hello World
.TP
\fBtask\fR
Task: Hello World
.TP
\fBwarning\fR
Warning: Hello World
