[package]
name = "fyi_witcher"
version = "0.1.7"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
itoa = "0.4.*"
jwalk = "0.5.*"
nix = "0.17.*"
num-format = "0.4.*"
rayon = "1.3.*"
regex = "1.3.*"
tempfile = "3.1.*"
tempfile-fast = "0.3.*"

[dependencies.indexmap]
version = "1.3.*"
default-features = false
features = [ "rayon" ]

[dependencies.fyi_msg]
path = "../fyi_msg"

[dependencies.fyi_progress]
path = "../fyi_progress"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fw_utility"
harness = false

[[bench]]
name = "fw_witcher"
harness = false
