[package]
name = "fyi_witcher"
version = "0.5.2"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "Path traversal helpers."
license = "WTFPL"
repository = "https://github.com/Blobfolio/fyi"
publish = false

[dependencies]
ahash = "0.6.*"
bytecount = "0.6.*"
crossbeam-channel = "0.5.*"
num-integer = "0.1.*"
rayon = "1.5.*"
regex = "1.4.*"
term_size = "0.3.*"

[dependencies.fyi_msg]
path = "../fyi_msg"
features = [ "fitted" ]

[dependencies.fyi_num]
path = "../fyi_num"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fw_utility"
harness = false

[[bench]]
name = "fw_witcher"
harness = false

[[example]]
name = "witcher"
