[package]
name = "fyi_witcher"
version = "0.2.6"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
itoa = "0.4.*"
jwalk = "0.5.*"
num-format = "0.4.*"
rayon = "1.3.*"
regex = "1.3.*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[dependencies.fyi_progress]
path = "../fyi_progress"

[dependencies.indexmap]
version = "1.4.*"
default-features = false
features = [ "rayon" ]

[dependencies.nix]
version = "0.17.*"
optional = true

[dependencies.tempfile]
version = "3.1.*"
optional = true

[dependencies.tempfile-fast]
version = "0.3.*"
optional = true

[dev-dependencies]
criterion = "*"

[features]
default = []
witch_io = [ "nix", "tempfile", "tempfile-fast" ]

[[bench]]
name = "fw_utility"
harness = false

[[bench]]
name = "fw_witcher"
harness = false

[[example]]
name = "witcher"
