[package]
name = "fyi_witcher"
version = "0.3.4"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
ahash = "0.4.*"
crossbeam-channel = "0.4.*"
num-integer = "0.1.*"
rayon = "1.4.*"
regex = "1.3.*"
term_size = "0.3.*"
unicode-width = "0.1.*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[dependencies.packed_simd]
version = "0.3.*"
optional = true

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fw_nice_elapsed"
harness = false

[[bench]]
name = "fw_utility"
harness = false

[[bench]]
name = "fw_witcher"
harness = false

[[example]]
name = "witcher"

[features]
default = []
simd = [ "packed_simd", "criterion/real_blackbox" ]
