[package]
name = "fyi_witcher"
version = "0.2.8"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
itoa = "0.4.*"
jwalk = "0.5.*"
num-format = "0.4.*"
rayon = "1.3.*"
regex = "1.3.*"

[dependencies.fyi_msg]
path = "../fyi_msg"

[dependencies.fyi_progress]
path = "../fyi_progress"

[dependencies.indexmap]
version = "1.5.*"
default-features = false
features = [ "rayon" ]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "fw_utility"
harness = false

[[bench]]
name = "fw_witcher"
harness = false

[[example]]
name = "witcher"
