[package]
name = "fyi_core"
version = "0.0.9"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
bytecount = "0.6.*"
chrono = "0.4.*"
num-traits = "0.2.*"
num-format = "0.4.*"
strip-ansi-escapes = "0.1.*"
term_size = "0.3.*"

[dependencies.ansi-escapes]
version = "0.1.*"
optional = true

[dependencies.defaults]
version = "0.2.*"
optional = true

[dependencies.dialoguer]
version = "0.5.*"
optional = true

[dependencies.nix]
version = "0.16.*"
optional = true

[dependencies.rayon]
version = "1.3.*"
optional = true

[dependencies.regex]
version = "1.3.6"
optional = true

[features]
default = []
interactive = [ "dialoguer" ]
progress = [ "ansi-escapes", "defaults" ]
witcher = [ "defaults", "nix", "rayon", "regex" ]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "scratchpad"
harness = false
