[package]
name = "fyi_core"
version = "0.0.7"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."
publish = false

[dependencies]
ansi_term = "0.12.*"
chrono = "0.4.*"
dialoguer = "0.5.0"
num-format = "0.4.0"
strip-ansi-escapes = "0.1.*"
term_size = "0.3.*"

[dependencies.ansi-escapes]
version = "0.1.*"
optional = true

[dependencies.nix]
version = "0.16.*"
optional = true

[dependencies.rayon]
version = "1.3.*"
optional = true

[dependencies.regex]
version = "1.3.6"
optional = true

[dependencies.walkdir]
version = "2.3.*"
optional = true

[features]
default = []
progress = [ "ansi-escapes" ]
witcher = [ "nix", "rayon", "regex", "walkdir" ]
