[package]
name = "fyi_core"
version = "0.0.1"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."

[dependencies]
ansi-escapes = "0.1.*"
ansi_term = "0.12.*"
chrono = "0.4.*"
strip-ansi-escapes = "0.1.*"
