[package]
name = "fyi_core"
version = "0.0.4"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "FYI is a dead-simple status message printer for CLI use applications."

[dependencies]
ansi-escapes = { version = "0.1.*", optional = true }
ansi_term = "0.12.*"
chrono = "0.4.*"
dialoguer = "0.5.0"
num-format = "0.4.0"
strip-ansi-escapes = "0.1.*"
term_size = "0.3.*"

[features]
default = []
progress = ["ansi-escapes"]
